### ISSUE TITLE
Plzz HELP nöt work

### ISSUE THREAD

**Issue by davidcetinkaya** [palmenhq/flymage-hello-world#1]
Not wokring wat time is it? Pleasze tell me. Dis not wörk how I install PLEEZZe

```javascript
console.log()
```

# 😱

**Comment by palmenhq** [comment]
@davidcetinkaya hahaha it’s _Java_ not JavaScript, silly ☕️

**Comment by davidcetinkaya** [comment]
I found fix prblm!

```javascript
document.write(😱)
```

Thankz suportt 🌟 !
